### ISSUE TITLE
[IDEA] RTL support

### ISSUE THREAD

**Issue by kookma** [clutterstack/TW5-quick#2]
I see when ctrl+shift is pressed the text direction in the text field of NoteAdder changed from ltr to rtl. This is quite handy for using NoteAdder with RTL language. Is it possible to show the notes (tiddler) created in view mode in RTL direction too. I mean a note in RTL is displayed in view mode in RTL direction.

**Comment by clutterstack** [comment]
@kookma I don't have RTL experience, so I'm not sure what would be needed to take advantage of this. Are you looking at the view mode in TiddlyWiki, or in my Omni plugin? 

...some reading later...

I have skimmed some of your comments at the TW5 repo, and I am now wondering: is it only that I am not respecting an i18n framework somehow? i.e. if you can read your normal tiddlers RTL, what am I missing?

**Comment by kookma** [comment]
@clutterstack What I see is only in Omni plugin!
Instead of ctrl+enter I pressed ctrl+shift and amazingly I saw the cursor shifted to right and I can write from right to left. So, I dont know if you added this feature intentionally or not but the text field of NoteAdder lets to write text from Right to Left!

When I save the note by control enter however the text is left aligned! I asked if you can manage to show such texts from right to left in View Mode!

**Comment by clutterstack** [comment]
@kookma I did not add anything intentionally. I think it is just that the browser has the capability to take input RTL or LTR from a text input, and my text input is a normal html one (not like the stock TIddlyWiki editor which has the toolbar/CodeMirror changing its behaviour).

I am way behind in understanding RTL support in TiddlyWiki. If you put the Omni plugin into the bidi-improvements branch TW, does the Omni tiddler text inherit the correct (RTL) display?

I tried to understand this by installing Omni and Quick into your TiddlySpot RTL test wiki. It looks OK to me, but I didn't enter anything, only copy-paste and adding existing tiddlers to the omnibus. And I cannot read it, so I am just trying to compare the order of words by shape. 

Can you confirm whether the above works for you, and if not, where does it fail?

**Comment by kookma** [comment]
@clutterstack 

> @kookma I did not add anything intentionally. I think it is just that the browser has the capability to take input RTL or LTR from a text input, and my text input is a normal html one (not like the stock TIddlyWiki editor which has the toolbar/CodeMirror changing its behaviour).

That is correct! ;-) Sorry, I did not know most browsers have such a great feature!

> 
> I am way behind in understanding RTL support in TiddlyWiki. If you put the Omni plugin into the bidi-improvements branch TW, does the Omni tiddler text inherit the correct (RTL) display?
> 
Seems it works!

> I tried to understand this by installing Omni and Quick into your TiddlySpot RTL test wiki. It looks OK to me, but I didn't enter anything, only copy-paste and adding existing tiddlers to the omnibus. And I cannot read it, so I am just trying to compare the order of words by shape.
> 
> Can you confirm whether the above works for you, and if not, where does it fail?

Yes, the Omni plugin woks fine!

Thank you for clarification on this!

**Comment by clutterstack** [comment]
Happy to hear it works! Now I've learned some things too.
